memory:
  vector_backend: "chromadb"
  episodic_db_path: "storage/episodic/memory.json"
  semantic_db_path: "storage/semantic/knowledge.json"
  procedural_repo_path: "storage/procedural"
tools:
  sandbox_root: "sandbox"
  allow_network: false  # Disables execution of networking binaries such as curl and wget.
  network_allowlist: []  # When allow_network is true, limit permitted networking binaries (empty means allow known binaries).
scheduler:
  max_concurrent_tasks: 1
  autonomous_task_interval_sec: 1800
  idle_sleep_seconds: 1.0
logging:
  level: "INFO"
  log_dir: "logs"
learning:
  feedback_path: "storage/analytics/feedback.json"
  max_feedback_history: 200
  dataset_path: "storage/learning/dataset.jsonl"
  dataset_flush_batch: 5
  min_samples_for_optimization: 10
  min_samples_for_training: 50
  success_rate_floor: 0.6
  success_rate_ceiling: 0.9
  optimizer_cooldown: 5
  min_autonomous_interval_sec: 300
  max_autonomous_interval_sec: 3600
  telemetry_cpu_threshold: 85.0
  telemetry_memory_threshold_mb: 1024.0
  training_strategy: "lora"
  training_base_model: "gpt2"
  training_output_dir: "storage/learning/models"
  training_metadata_path: "storage/learning/models/latest.json"
  training_overrides_path: "config/overrides.yaml"
  training_epochs: 1
  max_train_steps: 1000
  learning_rate: 5.0e-05
  lora_rank: 8
  dpo_beta: 0.1
logging:
  level: "INFO"
  log_dir: "logs"
