memory:
  vector_backend: "chromadb"
  vector_episodic_collection: "agi_episodic"
  vector_semantic_collection: "agi_semantic"
  chroma_connection: "http://localhost:8000"
  pgvector_dsn: "postgresql://agi:agi@localhost:5432/agi_memory"
  pgvector_table: "memory_records"
  pgvector_namespace_column: "namespace"
  pgvector_dimension: 1536
  episodic_db_path: "storage/episodic/memory.json"
  semantic_db_path: "storage/semantic/knowledge.json"
  procedural_repo_path: "storage/procedural"
tools:
  sandbox_root: "sandbox"
  allow_network: false
  browser:
    enabled: false
    headless: true
    default_timeout_ms: 10000
    allowed_origins: []
  rest:
    enabled: false
    default_timeout_sec: 10.0
    allowed_hosts:
      - "127.0.0.1"
      - "localhost"
    default_headers: {}
    auth_token: null
scheduler:
  max_concurrent_tasks: 1
  autonomous_task_interval_sec: 1800
  idle_sleep_seconds: 1.0
logging:
  level: "INFO"
  log_dir: "logs"
learning:
  feedback_path: "storage/analytics/feedback.json"
  max_feedback_history: 200
  dataset_path: "storage/learning/dataset.jsonl"
  dataset_flush_batch: 5
  min_samples_for_optimization: 10
  min_samples_for_training: 50
  success_rate_floor: 0.6
  success_rate_ceiling: 0.9
  optimizer_cooldown: 5
  min_autonomous_interval_sec: 300
  max_autonomous_interval_sec: 3600
  telemetry_cpu_threshold: 85.0
  telemetry_memory_threshold_mb: 1024.0
  training_strategy: "lora"
  training_base_model: "gpt2"
  training_output_dir: "storage/learning/models"
  training_metadata_path: "storage/learning/models/latest.json"
  training_overrides_path: "config/overrides.yaml"
  training_epochs: 1
  max_train_steps: 1000
  learning_rate: 5.0e-05
  lora_rank: 8
  dpo_beta: 0.1
logging:
  level: "INFO"
  log_dir: "logs"
